### ISSUE TITLE
warning in solution

### ISSUE THREAD

**Issue by rakzeee** [amannn/react-keep-state#2]
Is there the following warning in your (first) solution?

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

Can you say is it critical or I just don't need to worry about it?

**Comment by amannn** [comment]
My outlined solution shouldn't trigger this warning. My guess is that this is somewhere in your own component code.

Generally I'd recommend to check what is causing the issue.
